"""Add User, IPUsage models and update Template model

Revision ID: 0090cbb69f15
Revises: 0b0c454aa99c
Create Date: 2025-10-31 12:40:45.731762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0090cbb69f15'
down_revision = '0b0c454aa99c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=False),
    sa.Column('last_attempt_date', sa.Date(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('ip_address')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=80), nullable=False),
    sa.Column('password_hash', sa.String(length=128), nullable=True),
    sa.Column('sso_id', sa.String(length=128), nullable=True),
    sa.Column('daily_api_calls', sa.Integer(), nullable=True),
    sa.Column('last_api_call_date', sa.Date(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sso_id'),
    sa.UniqueConstraint('username')
    )
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key('fk_template_user_id_user', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('template', schema=None) as batch_op:
        batch_op.drop_constraint('fk_template_user_id_user', type_='foreignkey')
        batch_op.drop_column('user_id')

    op.drop_table('user')
    op.drop_table('ip_usage')
    # ### end Alembic commands ###
