"""Add progress columns to Job table

Revision ID: 6795a1da368a
Revises: ca0a4aaac7b4
Create Date: 2025-11-12 07:47:15.602390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6795a1da368a'
down_revision = 'ca0a4aaac7b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress_percentage', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('progress_message', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('processing_time_seconds', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('job', schema=None) as batch_op:
        batch_op.drop_column('processing_time_seconds')
        batch_op.drop_column('progress_message')
        batch_op.drop_column('progress_percentage')

    # ### end Alembic commands ###
