"""Add usage_limit to User model

Revision ID: ca0a4aaac7b4
Revises: afe095ba1c1a
Create Date: 2025-11-02 04:09:23.488663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca0a4aaac7b4'
down_revision = 'afe095ba1c1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('usage_limit', sa.Integer(), nullable=False, server_default='5'))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('usage_limit')

    # ### end Alembic commands ###
